# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Telo Therapeutics
email: info@telotherapeutics.com
description: > # this means to ignore newlines until "baseurl:"
  Telo Theraputics utilizes a novel precision medicine approach to reverse cancer cell immortality.
baseurl: ""
url: "http://telotherapeutics.com" 
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
